qualisys_driver_node:
  ros__parameters:
    stream_mode: "ClientPull"
    host_name: "mocap"
    host_port: 22222
    tf_ref_frame_id: "qualisys_world"
    tracked_frame_suffix: "qualisys"
    publish_markers: true
    marker_data_enabled: false
    unlabeled_marker_data_enabled: false
    last_frame_number: 0
    frame_count: 0
    dropped_frame_count: 0
    n_markers: 0
    n_unlabeled_markers: 0
    qos_history_policy: "keep_all"         # keep_all / keep_last
    qos_reliability_policy: "best_effort"  # best_effort / reliable
    qos_depth: 10                         # 10 / 100 / 1000
